"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def ispentagonal(x):
    n=1
    while True:
        number =n*(3*n-1)/2
        if number<x:
            n+=1
            continue
        elif number > x:
            return False
        else:
            return True
def ishexagonal(x):
    n=1
    while True:
        number =n*(2*n-1)
        if number<x:
            n+=1
            continue
        elif number > x:
            return False
        else:
            return True
a=2
counter=0
while True:
    number = a * (a + 1)/2
    if ispentagonal(number) and ishexagonal(number):
        print(int(number))
        counter+=1
        if counter==2:
            break
    a+=1